Repository RoboCupAtHome/RuleBook, pull requests merged in 2019-02, with the labels that each got.

#517 Clean Up
  scoresheets/CleanUp.tex
  tasks/CleanUp.tex
Labels: Scenario: Household Chores, Stage-1

#520 Storing Groceries
  scoresheets/StoringGroceries.tex
  tasks/StoringGroceries.tex
Labels: Scenario: Household Chores, Stage-1

#529 Added the General Purpose Service Robot task.
  Rulebook.tex
  scoresheets/GPSR.tex
  tasks/GPSR.tex
Labels: Scenario: Household Chores, Stage-1

#548 Added a task called Carry my Luggage in Stage I.
  Rulebook.tex
  scoresheets/CarryMyLuggage.tex
  scoresheets/HelpMeCarry.tex
  tasks/CarryMyLuggage.tex
Labels: Scenario: Party Host, Stage-1

#544 Stickler for Rules Task
  Rulebook.tex
  scoresheets/SticklerRules.tex
  tasks/SticklerForRules.tex
Labels: Scenario: Party Host, Stage-2

#526 Add the Find my Disk task
  Rulebook.tex
  general_rules/Scenario.tex
  images/find_my_disk.png
  scoresheets/FindMyDisk.tex
  tasks/FindMyDisk.tex
Labels: Scenario: Household Chores, Stage-2

#546 Hand Me That Task
  Rulebook.tex
  scoresheets/HandMeThat.tex
  tasks/HandMeThat.tex
Labels: Scenario: Party Host, Stage-2

#543 Where is This? Task
  Rulebook.tex
  scoresheets/WhereIsThis.tex
  tasks/WhereIsThis.tex
Labels: Scenario: Party Host, Stage-2

#561 Buff and enhance the Smoothie Chef task based on PR #554
  scoresheets/SmoothieChef.tex
  tasks/SmoothieChef.tex
Labels: Scenario: Household Chores, Stage-2

#554 Add the Smoothie Chef task
  Rulebook.tex
  scoresheets/SmoothieChef.tex
  tasks/SmoothieChef.tex
Labels: Scenario: Party Host, Stage-2

#527 Add (Refactored) Restaurant test
  Rulebook.tex
  scoresheets/Restaurant.tex
  tasks/Restaurant.tex
Labels: Scenario: Party Host, Stage-2
